name: kproto
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- feather-format=0.4.0
- jupyter=1.0.0
- matplotlib=3.1.1
- numpy=1.17.4
- pandas=0.25.3
- pyarrow=0.13.0
- scikit-learn=0.21.2
- seaborn=0.9.0
- kmodes=0.11.0
- pip
- pip:
  - ipython==7.10.1
